### ISSUE TITLE
Wrong country translation (Turkey) in German

### ISSUE THREAD

**Issue by ozfloyd** [hbb20/CountryCodePickerProject#106]
Hi, thanks for your great coding !
I've faced a serious issue with the translation of Turkey in German country list.
It should be "Türkei" instead of "Truthahn" (pls check here for ref: http://www.nationsonline.org/oneworld/countrynames_german.htm)

Also Turkey flag color seems orange, while it should be red. Please check here for ref: https://en.wikipedia.org/wiki/Flag_of_Turkey

It will be great if you can fix it quickly, thanks again !

**Comment by hbb20** [comment]
Thanks for the correction. I will update in next version. This will help
all CCP users.

**Comment by ozfloyd** [comment]
Thanks Harsh for your quick reply.
When can we expect the next version?

**Comment by hbb20** [comment]
Running busy this week. How long can you wait?
I was looking for another help. Can you please check all other names in the
same language?

**Comment by ahmetkocabiyik** [comment]
We are together with @ozfloyd . We have to publish an app using your library. If you could update only changes that @ozfloyd mention about as soon as possible we will be so glad. We are waiting for your update to publish the app.

**Comment by ozfloyd** [comment]
Let's wait then, but it would be better to get asap.
Actually I'm not good at German but I'll drop a note here if I find an issue.

**Comment by hbb20** [comment]
I am not sure when I will be able to release new version. 
so here is a quick fix for you.

1. Open [this link ](https://goo.gl/rBLWr2). You will find two folders. "/raw" and "/drawable-nodpi"
2. Copy both folders in your app's res folder. so that it becomes "res/raw" and "res/drawable-nodpi" (if you already had these folders, then simple merge these with your existing)
3. Menu > Build > Clean Project
4. Menu > Build > Rebuild Project
5. Run the app. It should give you expected fix.

Let me know your status after doing this.

**Comment by ozfloyd** [comment]
Hi, it worked! Thanks for your quick action and solution!
Have a good day!

**Comment by Agraphie** [comment]
I went through the whole list and correct some.
