### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by beersheba** [hbb20/CountryCodePickerProject#12]
I want to add hebrew localization to this picker. How to do it?

**Comment by hbb20** [comment]
To add new language follow the given steps:

1. Add language to the [List](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L39). Assign number in order so that it does not clash with any other country above.

2. Add language enum [here](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L39).

3.  Add index -> enum conversion [here](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L417).

4. Add custom language [Dialog title](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L417), [Search hint](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L483) and [No result message](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/CountryCodePicker.java#L525) text.

5. Add method to return list in custom language [here](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/Country.java#L2776). In your case it will be getLibraryMasterCountriesHebrew().

6. Add language to master list [switch case](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/java/com/hbb20/Country.java#L223).

7. To assign country from xml layout, add language to [attr](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/values/attrs.xml#L24). You must assign the same number which you assigned in step 1. 

_All provided links are from this [commit](https://github.com/hbb20/CountryCodePickerProject/tree/d9e17570075747e02ace6f695e2e69fa717b0af1) (In case of change in files)_

**Comment by beersheba** [comment]
I did it successfully, thank you for the guideline. Btw, i found some translation issues, for example country name "Togo" translated to another languages as "to go" sentence, or Turkey translated as dinde (turkey) to French and Peru on Portugese.

Also RTL is not supported, this can be done by slightly changing the xml. I did it in CountryCodeViewHolder constructor like this:

`            RelativeLayout.LayoutParams name_params = (RelativeLayout.LayoutParams) textView_name.getLayoutParams();
            name_params.addRule(RelativeLayout.LEFT_OF, R.id.textView_code);
            name_params.addRule(RelativeLayout.START_OF, R.id.textView_code);

            RelativeLayout.LayoutParams code_params = (RelativeLayout.LayoutParams) textView_code.getLayoutParams();
            code_params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
            code_params.addRule(RelativeLayout.ALIGN_PARENT_END);

            textView_code.setTextDirection(View.TEXT_DIRECTION_LTR);`
