### ISSUE TITLE
Default Country

### ISSUE THREAD

**Issue by ptahsohn** [hbb20/CountryCodePickerProject#121]
Default Country not working anymore from version 8.0.5-8 for Country Kenya,"KE" even when setting it on the xml or programmatically until one calls resetToDefaultCountry() manually.
Not fully tested with all other countries but seems by default its US.
Regards

**Comment by hbb20** [comment]
Actually, auto detect country is by default true. You need to [set it false](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccp_autodetectcountryfalse-default--true-) to load the default country. What is changed in 8.0.5 is the way to detect the country. Up to 8.0.5 was detecting country correctly so default country and detected country were the same for you. What we changed in 8.0.5 is faulty 
 that's why you are facing the problem. We are working on it.
