### ISSUE TITLE
Dialog title style and Seach edittext hint

### ISSUE THREAD

**Issue by kurosaki-tisak** [hbb20/CountryCodePickerProject#135]
Please.. I want to change a style of dialog title and edittext hint
I don't see any of these in wiki ;)

Thanks

**Comment by hbb20** [comment]
Right now, CCP gives the option to change the [color of](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Dialog-Theme-Customization) text and [typeFace ](https://github.com/hbb20/CountryCodePickerProject/wiki/Custom-TypeFace-(FontFamily)#use-custom-typeface)of those.

If you want to customize other properties. Do following.
1. Add [layout_picker_dialog.xml](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/layout/layout_picker_dialog.xml) to your `layout/` folder.
2. Add/modify properties in this local file.
3. Now run the project. It will pick your layout file instead of library's default.

*You might not be able to change some properties as CCP is setting them at the runtime.*

Hope this will be helpful.
