### ISSUE TITLE
how to edit countries list

### ISSUE THREAD

**Issue by zaheerpoei** [hbb20/CountryCodePickerProject#138]
i want to update countries list and their codes because some countries are missing and some country codes are wrong.

**Comment by hbb20** [comment]
If the country is missing or have wrong code, we will like to add or correct it so that it can be helpful to all other developers.
1. You can create a pull-request after correcting the phone codes
2. You can create a pull-request after adding the new country. (Following the [guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Guide-to-add-new-country-in-list))
3. You can suggest that in an issue, we will add / correct them. Usually, this takes longer than other two.

**Comment by caramelWaffle** [comment]
Does country codes correct now?

**Comment by hbb20** [comment]
Please post the list of countries with incorrect country code.
