### ISSUE TITLE
invalid translate arabic 

### ISSUE THREAD

**Issue by WahdanZ** [hbb20/CountryCodePickerProject#142]
ccp_dialog_no_result_ack_message  has invalid translte 
"يؤدي لم يتم العثور" **invalid** 
should be
"لايوجد نتائج" **valid**

**Comment by hbb20** [comment]
Thank you so much for reporting. I will correct this message translation in the upcoming release.

Translation errors are due to the simple google translation of country names. [Developers](https://github.com/hbb20/CountryCodePickerProject#credits) from all over the world are correcting errors in their native language translation to be helpful to other developers. 

If Arabic is your native language, is it possible for you to go through entire [arabic](https://github.com/hbb20/CountryCodePickerProject/blob/master/ccp/src/main/res/raw/arabic.xml) translation file and correct all the incorrect translations?

**Comment by WahdanZ** [comment]
yes, I will do it ASAP. 
and thanks for the awesome library

**Comment by WahdanZ** [comment]
this correct countries name with Arabic translate,

https://gist.github.com/WahdanZ/8f720718b31727e3a20cc35b07668fe5

**Comment by hbb20** [comment]
Thank you so much for the help. I will update this in the upcoming version and release it soon.... 👍

**Comment by hbb20** [comment]
Version 2.1.2 of CCP has corrected translations for Arabic. Thank you @WahdanZ again for corrections.

**Comment by MoustafaElsaghier** [comment]
@WahdanZ did you found any issues when using this lib in Arabic? the box is hidden for me and must put attribute                         android:layoutDirection="ltr"
which fails the dialog firections
