### ISSUE TITLE
Hi, I had this error when using your library version 2.1.5, I attached the error detected by Crashlytics: com.hbb20.CountryCodeAdapter$4.onClick (CountryCodeAdapter.java:195)

### ISSUE THREAD

**Issue by JoynerPerez1987** [hbb20/CountryCodePickerProject#174]

**Comment by hbb20** [comment]
Sorry for the trouble.
Actually, something is broken in library uploader config (bintrayUpload) due to changing gradle version and implementation. So temporarily, I have switched back to compile. You can use version 2.1.9. Meanwhile, I will look for a way to change from compile to implementation or api.
