### ISSUE TITLE
Abbreviation for United Kingdom

### ISSUE THREAD

**Issue by tavar** [hbb20/CountryCodePickerProject#175]
Hello,

when I choose the country United Kindom (GB) and the dialogue closed, the spinner is showing the wrong abbreviation.

Instead of GB +44 or maybe UK +44 there stands IM +44.

Maybe it is related to this #168  issue, but I'm using the newest version 2.1.9.

Thanks,
Andreas

**Comment by hbb20** [comment]
Sorry about that. When we tried the explained scenario in our sample project, we could not reproduce the issue. We might need more details to regenerate and fix the problem.

Note: (+44 1624 xxxx) are Isle of Man country numbers so if you start typing with 1624, CCP will automatically change GB to IM.)

- Have you set carrier phone editText?
- Can you post the XML and Java Code so that we can check with the exact case?
