### ISSUE TITLE
country names with quote display issue

### ISSUE THREAD

**Issue by mathieuales** [hbb20/CountryCodePickerProject#178]
Hi !
country names with quote are not displayed correctly :
 in french `ivory coast` is displayed as `Côte D &apos; ivoire` instead of `Côte d'ivoire`

Thanks

**Comment by hbb20** [comment]
Thank you for reporting. We have updated the name in code and will reflect in the upcoming version. 

Even there might be problems in country name translations due to simple Google Translate. If you know the French and can check all the country names for the French language then it will be helpful to the Android community. If you decide to do it, you can list the corrections here in the comment or create a PR.

**Comment by mathieuales** [comment]
Hi !
Just made a PR #188 
Thx
