### ISSUE TITLE
Wrong Ukraine code +380

### ISSUE THREAD

**Issue by vaderot** [hbb20/CountryCodePickerProject#182]
For correct auto format with ukranian numbers code should be +38. Now is +380. It is in com.hbb20.CCPCountry.java line 1084. Please fix it

**Comment by hbb20** [comment]
Well +380 is correct international code for Ukraine (https://countrycode.org/ukraine). Reason for this issue may be because of a problem in autoformat. If national format number starts with 0 then it won't format unless user starts typing number with 0. 

We are looking forward to solving this issue. If you find something, please let us know.

**Comment by vaderot** [comment]
If 0 is a part of code, and needed for formatting, may be you can put it as a first undelated symbol in carrierNumberEditText?
If not i think you should just delete 0 from international code. In our country all people start writing their phone number from that 0. Even I didnot mention that there is 0 in country code for the first several times. And wrote smth like +380 098 123 4567. I think first zero in code is not needed

**Comment by hbb20** [comment]
Try version 2.2.0 of the library that should solve this formatting issue. If the problem persists please post back here with details, I will reopen the issue.

**Comment by vaderot** [comment]
solved. thank you
