### ISSUE TITLE
Valid output of `fullNumber` doesn't revalidate

### ISSUE THREAD

**Issue by otormaigh** [hbb20/CountryCodePickerProject#208]
Setting the text field to the output of  `fullNumber`, `fullNumberWithPlus` or `formattedFullNumber` and calling `isValidFullNumber` again returns `false`.

```
editText.setText(/*some valid number*/)
assertThat(countryCodePicker.isValidFullNumber).isTrue

editText.setText(countryCodePicker.fullNumber)
assertThat(countryCodePicker.isValidFullNumber).isTrue // this fails
```

**Comment by hbb20** [comment]
Alright. Looks like `countryCodePicker.fullNumber` is used incorrectly and it is causing problem.
Let's assume:
Country code: +91 (Comes from CCP)
Valid Number: 8866607722 (Comes from EditText)
Full Number +918866607722 (Full Number which is tested for validity)

In the first test, you are passing valid number (8866607722) to edit text and selected country is IN (+91). isValidFullNumber() will make full number by combining code and number (in this case it will be +918866607722). This is valid full number.

Now let's check 2nd test. After end of first test, your fullNumber() will return "918866607722". By `editText.setText(countryCodePicker.fullNumber)` you are setting "918866607722" in edit text. Now 2nd assert's isValidFullNumber will check "+91918866607722" and which is invalid for sure because instead of carrier number, full number is in editText. You might want to use [`countryCodePicker.setFullNumber()`](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support#5-load-full-number) in 2nd test. Check more on [wiki page](https://github.com/hbb20/CountryCodePickerProject/wiki/Full-Number-Support)
