### ISSUE TITLE
Change country code color 

### ISSUE THREAD

**Issue by hiteshsahu** [hbb20/CountryCodePickerProject#209]
I need to change color of country code to white

I tried setting  `countryCode.setContentColor(R.color.white);` but diidnt work. Any helper method would be great or xml attribute to change text color.

**Comment by hbb20** [comment]
Hello @hiteshsahu , [Wiki Page](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Theme-Customization#custom-content-color) for custom color should be helpful.

setContentColor() expect color instead of color res. So instead of `countryCode.setContentColor(R.color.white);` you should use  `countryCode.setContentColor(getResources().getColor(R.color.white));`

For XML option and more, check [Wiki Page](https://github.com/hbb20/CountryCodePickerProject/wiki/CCP-Theme-Customization#custom-content-color)

**Comment by mwshubham** [comment]
XML option is as follows
`app:ccp_contentColor="@android:color/white"`
