### ISSUE TITLE
Validate if phone number is correct

### ISSUE THREAD

**Issue by ceddyb** [hbb20/CountryCodePickerProject#24]
How can i achieve this with your library?

For example if i choose country then i enter phone number, how do i run a test to check if the full number entered is correct

**Comment by ceddyb** [comment]
I think this might work

`PhoneNumberUtils.isGlobalPhoneNumber("120121852f4")`

**Comment by ceddyb** [comment]
Please add that method in your lib

**Comment by hbb20** [comment]
Hi Ceddy Mahoza, that's really a good idea to integrate validation in lib
it self. Will do it in next release... Till then developer can use
PhoneUtil manually to validate the phone number.

On Fri, 9 Dec 2016 at 16:51, Ceddy Muhoza <notifications@github.com> wrote:

Please add that method in your lib

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hbb20/CountryCodePickerProject/issues/24#issuecomment-265991810>,
or mute the thread

**Comment by ceddyb** [comment]
Another issue, 

Am trying to get the values entered in the editText_registeredCarrierNumber, 

I think it can be a great idea to add an interface to listen to OnTextChange, that way we can run some checks to validate the full number in real time, 

Maybe i should open a new thread for this

Thanks

**Comment by hbb20** [comment]
Point noted. Definitely full number support can have the feature what you
asked for along with many more like correct formatting but it will take
some time to set everything in place correctly.

**Comment by ceddyb** [comment]
Am customizing your code, if it works i'll pull a request and save you time.

Much respect for your great lib, thanks

**Comment by hbb20** [comment]
Sure, pull requests are always welcome for betterment.

**Comment by ceddyb** [comment]
This guy is trying to do the same but his lib is not better than yours https://github.com/AlmogBaku/IntlPhoneInput

**Comment by hbb20** [comment]
Yeah, that guy has done real good work. It might be helpful for us when we will add more support for full number in our library.

**Comment by hbb20** [comment]
Hey @ceddyb version 2.0.0 has method **isValidFullNumber()** which can be used to check if entered full number is correct or not.

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.
