### ISSUE TITLE
Failed to resolve dependency issue

### ISSUE THREAD

**Issue by vzizmiyagi** [hbb20/CountryCodePickerProject#28]
I am totally new to android (< a month) and I am building basic apps to improve. I have been trying to setup a way for the app to retrieve area code along with a user's phone number when I stumbled on your library.

However, I can't seem to add it to my project. I get the following error at the very first step:

    Error:(25, 13) Failed to resolve: com.hbb20:ccp:1.7.1 Show in File
    Show in Project Structure dialog

Thank you in advance for your input/help. My bad if this is an obvious question.

**Comment by hbb20** [comment]
I assume and hope that you are using Android Studio, not eclipse.

This might happen when you add library dependency in gradle file but during
sync it can't reach to jcenter (where libraries are hosted) server.

Make sure you have an active Internet connection to reach jcenter and then
try to rebuild project from Build (Menubar)->Rebuild project.

If (error persists)
{ click on "Show in Project Structure dialogue" in error message and send
resulting screenshot along with your gradle file. As it's just testing
project you can send me repository link to my mail.}
else
{close this issue 😊.}
On Tue, 13 Dec 2016 at 03:50, vzizmiyagi <notifications@github.com> wrote:

I am totally new to android (< a month) and I am building basic apps to
improve. I have been trying to setup a way for the app to retrieve area
code along with a user's phone number when I stumbled on your library.

However, I can't seem to add it to my project. I get the following error at
the very first step:

Error:(25, 13) Failed to resolve: com.hbb20:ccp:1.7.1 Show in File
Show in Project Structure dialog

Thank you in advance for your input/help. My bad if this is an obvious
question.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hbb20/CountryCodePickerProject/issues/28>, or mute the
thread

**Comment by vzizmiyagi** [comment]
Yes I am using Android studio and my internet connexion works. I have attached the screenshots and emailed you the project.
Again I apologize for the inconvenience.
Thank you again.

![screen shot 2016-12-13 at 08 41 26](https://cloud.githubusercontent.com/assets/24533266/21134091/193f602a-c114-11e6-88ab-adee7fd1dde6.png)
![screen shot 2016-12-13 at 09 09 39](https://cloud.githubusercontent.com/assets/24533266/21134092/19466096-c114-11e6-8361-2806241f3900.png)

**Comment by vzizmiyagi** [comment]
Hello,
I made it work by creating the app, adding the library and then adding parse not the other way around.
Thanks, issue closed!

**Comment by hbb20** [comment]
Well that's interesting. You mean order in gradle made the difference right?

**Comment by vzizmiyagi** [comment]
Yes the order is different but instead of starting with a Parse-Starter-Project, I created a test app, added the library and then followed the quick start to add parse to an existing project.

**Comment by hbb20** [comment]
Ohkz.. Glad to know that it's working for you ✌🏼👍🏼
