### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by im-ranu** [hbb20/CountryCodePickerProject#301]
Android resource linking failed
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xm
error: resource android:attr/dialogCornerRadius not found.
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v28\values-v28.xml
error: resource android:attr/dialogCornerRadius not found.
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml error: resource android:attr/fontVariationSettings not found.
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
error: resource android:attr/ttcIndex not found.
error: failed linking references.

**Comment by CorleoneAM** [comment]
Solution?

**Comment by im-ranu** [comment]
Yes want solution

**Comment by hbb20** [comment]
Seems like your problem is related to android P and the mentioned missing resources has nothing to do with this library. As answered [here](https://stackoverflow.com/questions/49249713/can-not-build-the-project-after-upgrading-to-android-p), 

Change the compileSdkVersion to:

`compileSdkVersion 28`
