### ISSUE TITLE
io.michaelrocks is not resolved on Gradle Build plugin 3.4.1 & Gradle 5.1.1 & AS 3.4.1

### ISSUE THREAD

**Issue by Drjacky** [hbb20/CountryCodePickerProject#315]
@hbb20 

When I set these, my project can not build:
```
classpath 'com.android.tools.build:gradle:3.4.1'

distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

Android Studio version: 3.4.1
```
And when I explicitly defining the:
`implementation 'io.michaelrocks:libphonenumber-android:8.10.12-1'`
In my `build.gradle`, it works.

I guess the working solution is changing this line in your `CountryCodePickerProject/ccp/build.gradle` file:
`Implementation 'io.michaelrocks:libphonenumber-android:8.10.1'`
To
`api 'io.michaelrocks:libphonenumber-android:8.10.12-1'`

**Comment by hbb20** [comment]
I tired with the same configuration you mentioned but mine worked as expected.

One thing I can think of is this can be an issue of library version 2.1.5 (or something around). Problem happened due to the library was not added in the metadata so dependency was fetch in consumer app. Check https://github.com/hbb20/CountryCodePickerProject/issues/173 

But this should not happen in the latest version of library. Please post back if this is happening in latest version. I will reopen the issue.

**Comment by Drjacky** [comment]
@hbb20 But I'm using `2.2.9` version.
Please try again but this time, use gradle command to clean and build your sample project.
