### ISSUE TITLE
country picker with cities

### ISSUE THREAD

**Issue by hvar90** [hbb20/CountryCodePickerProject#327]
is possible to add other picker with the cities of each country selected ?
using this JSON
https://raw.githubusercontent.com/David-Haim/CountriesToCitiesJSON/master/countriesToCities.json

**Comment by hbb20** [comment]
This is really creative and useful idea. Thank you for the suggestion. We might not add this feature for this library because  pick up country code (for phone number) is Country Code Picker's core focus. The "Country Picker" is a natural extension of this library so we support it just as a secondary use-case. 

I believe, if you want to build city picker you can definitely use this library for first part where you need a Country Picker. Thank you for your interest and understanding. 👍
