### ISSUE TITLE
accessing countryCodePicker.imageViewFlag returns null

### ISSUE THREAD

**Issue by PieterVenter77** [hbb20/CountryCodePickerProject#332]
whenever I try to access `countryCodePicker.imageViewFlag` inside  `countryCodePicker.setOnCountryChangeListener`, it seems like the imageViewFlag is always null or it has no drawable ? is there any other way i can access the flag drawable for a selected country ? 

What im trying to achieve : on select of a location from the dialog, get the flag resource so that i can show the flag

**Comment by PieterVenter77** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/26046935/61717758-f677f380-ad61-11e9-9a53-635e5b7e59f6.png">
I think there might be an issue with the way this is handled here, as you set the image resource AFTER invoking the callback

**Comment by hbb20** [comment]
Thank you for reporting. We just released new version `v2.3.0` with the fix. Please check and let us know if it does not work as expected.

**Comment by khanfarhat** [comment]
countryCodePicker.imageViewFlag is not returning selected country flag. I am getting flag of previously selected country

**Comment by hbb20** [comment]
@khanfarhat I just wanted to confirm the version that you are using. Versions prior to 2.3.0 had this problem and we think we have solved it in 2.3.0. Please let us know if it's happening on 2.3.0. Also can you or @PieterVenter77 explain the use case where you need to fetch flag explicitly. We would like to provide official API for that so that you do not need to find work arounds.

**Comment by PieterVenter77** [comment]
I apologize for responding so late, it's been a busy few weeks (I'm sure you'll understand how that feels)

So, I ended up cloning the library locally and making these changes myself, but after changing it as I suggested it DID work like I was hoping it would. I have to commend you on making an excellent library! I am almost disappointed that I have to be using your library instead of android providing us such a component. 

My use-case: I did not want to show the "edit text" component you guys use (the `com.hbb20.CountryCodePicker` component,  I just wanted the dialog to be shown. So what I ended up doing was adding in your "Edit text" looking `com.hbb20.CountryCodePicker` and made it invisible, then on click of my components I would show the dialog and from the result of the dialog I would use the flags, text and country code for my specific layout. Hope this makes sense, I wasn't sure if there's purely a dialog option for the library so I had to use it as a dialog essentially. Possibly a future feature for you if you ever have the time. Let me know if you have any questions, thanks again for an amazing library and sorry for my late reply

**Comment by hbb20** [comment]
Thanks for the response @PieterVenter77. Since the library was originally designed to be used as a country *code* picker we never thought of use cases like this and so there isn't any "Only Dialog" option available. But your detailed explanation makes total sense. We are already working to give first class support for country picker. This will help us designing that.
