### ISSUE TITLE
autoformat number and phone number validation not working with certain numbers

### ISSUE THREAD

**Issue by CodeIsmail** [hbb20/CountryCodePickerProject#422]
Hi.
I've two cases with phone numbers from two different countries

1. A Benin Republic mtn phone number starting with +229 51 is considered an invalid phone number and not properly formatted
![Screenshot_20200716-100030_RightQ Kiosk](https://user-images.githubusercontent.com/8437935/87669048-2d11ff80-c765-11ea-9c15-f2ffedc099bb.jpg)

2. A Nigerian Phone starting with +234 70 becomes valid with incomplete phone number digits(7). eg +234 703 240 is incomplete but considered as valid instead of +234 703 240 0000
![Screenshot_20200716-095817_RightQ Kiosk](https://user-images.githubusercontent.com/8437935/87668480-0c957580-c764-11ea-81ac-351ef175d392.jpg)

**Comment by hbb20** [comment]
CCP simply uses [libphonenumber](https://github.com/MichaelRocks/libphonenumber-android) for validation. I checked on some other website to check validity and they match the CCP result:

![image](https://user-images.githubusercontent.com/4918760/87846611-4e223f80-c88e-11ea-9019-63cf4e27c793.png)

![image](https://user-images.githubusercontent.com/4918760/87846561-ff74a580-c88d-11ea-96ea-bc7dfd981c80.png)

![image](https://user-images.githubusercontent.com/4918760/87846556-f7b50100-c88d-11ea-91df-cdacc6298782.png)
 
![image](https://user-images.githubusercontent.com/4918760/87846536-d9e79c00-c88d-11ea-8110-725153df27e6.png)

Probably this is because I am testing after updating the libphonenumber to the latest. I'll be releasing a new version of CCP that should solve the issue.

**Comment by hbb20** [comment]
Please try `v2.4.1`. If you still face this issue, then feel free to comment back.

**Comment by CodeIsmail** [comment]
Case 1 is working fine now after changing the version.
For case 2, valid numbers are usually  13 digits with country code. Eg
This is valid.
+234 818 348 2344.
+234 703 682 2335. 

This shouldn't be valid
+234 703 682 2 (7 digits)
