### ISSUE TITLE
Error:(700) Attribute "textSize" already defined with incompatible format.

### ISSUE THREAD

**Issue by lpraneeth** [hbb20/CountryCodePickerProject#46]
When I try to include CCP using gradle I'm getting this error!

after searching a lot I finally found solution:
but I cant change it in the library please update this in ur library

<declare-styleable name="CountryCodePicker"><attr format="integer" name="defaultCode"/><attr format="color" name="contentColor"/><attr format="dimension" name="textSize"/><attr format="dimension" name="arrowSize"/><attr format="string" name="countryPreference"/><attr format="string" name="defaultNameCode"/><attr format="boolean" name="hideNameCode"/><attr format="enum" name="ccpLanguage">

the field textSize is already used by some other library in my project when I edit that line and build the project it dint show any error but after getting library I cant inflate the CCP in the project pls fix this

**Comment by hbb20** [comment]
Yeah that happens with such common attributes.

I will add prefix cpp_ to all properties to avoid such conflict in next
version.

For now you can try one thing.
You must be using

    xmlns:app="http://schemas.android.com/apk/res-auto/>

Name space "res-auto".  Try by specifying namespace of CCP in CCP view.

    xmlns:app="http://schemas.android.com/apk/res/com.hbb20.countrycodepicker"


Or

xmlns:app="http://schemas.android.com/apk/res/com.hbb20"



I'm not sure if it will work or which will work. But those properties are
picked from name space so it is worth trying. You might need to correct the
name as I have put it without development machine.

Keep us updated with the progress.


On Sun, 9 Apr 2017 at 16:56, L Praneeth Kumar <notifications@github.com>
wrote:

When I try to include CCP using gradle I'm getting this error!

after searching a lot I finally found solution:
but I cant change it in the library please update this in ur library

the field textSize is already used by some other library in my project when
I edit that line and build the project it dint show any error but after
getting library I cant inflate the CCP in the project pls fix this

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hbb20/CountryCodePickerProject/issues/46>, or mute the
thread

**Comment by Binzzzz** [comment]
I couldn't make a build for that, could you pls add this and get me the same in the Gradle build library??

**Comment by hbb20** [comment]
Adding "ccp_" prefix for attributes. You will get it in v2 of library.

**Comment by hbb20** [comment]
Hey @lpraneeth and @Binzzzz  please upgrade to vesrion 2.0.0. 
Now all attributes has prefix _ccp__  / _ccpDialog__ to avoid name clashes.

Please read [update guide](https://github.com/hbb20/CountryCodePickerProject/wiki/Update-Guide-for-v2.0.0) before upgrading to v2.0.0.

**Comment by tintomathew** [comment]
I have textview size related issue. I am using the same text size and view size for the code picker and for the phone number edit text. And the code picker text is getting cropped. Pls reply soon. I need to release the app at the earliest

**Comment by hbb20** [comment]
Just want make sure that you are using `app:ccp_textSize` instead of `android:textSize`, right?

**Comment by hbb20** [comment]
Also can you please send me the layout file you are using... It seems like this can be an issue of bounds within layout.

**Comment by pawanuser** [comment]
Could not find method implementation() for arguments [com.hbb20:ccp:2.4.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.  Error show during implementation of ccp.

**Comment by hbb20** [comment]
oops.. not sure why.. can you try 2.5.0?
