### ISSUE TITLE
Hide Telephone code?

### ISSUE THREAD

**Issue by Isabellle** [hbb20/CountryCodePickerProject#54]
Quick question regarding your awesome library :)
Can I do something to hide it on the dialog? Thank you very much

**Comment by hbb20** [comment]
Library is basically built for the phone codes so there is no way to hide
Phone code. You can clone the project and hide that text view.

Are you planning to use this library as country selector instead of phone
code selector? Please let me know what is your exact use case. This will
help us cover other possible use cases of library in upcoming versions.

**Comment by Isabellle** [comment]
Thank you for your really quick reply. You are right regarding the usage I plan to make; more a country selector rather than a Phone code picker. I totally understand that this request is not in the same direction as your library.

**Comment by Pradeep0801** [comment]
Yes i am  planning to use this library as country selector instead of phone
code selector , is there any way to hide phone codes???

**Comment by hbb20** [comment]
Finally you can hide phone code from CCP.
Use version **1.7.7** of library
Add `app:ccp_showPhoneCode="false"`.
This will hide phone code from ccp and ccp_searchBox.

Refer [guidelines](https://github.com/hbb20/CountryCodePickerProject#16-use-as-country-selector) for more details.
