### ISSUE TITLE
defaultNameCode not working

### ISSUE THREAD

**Issue by ArmandoGomez** [hbb20/CountryCodePickerProject#76]
app:ccp_defaultNameCode="MX" not working i also use Spain ES, and German DE without any result

**Comment by hbb20** [comment]
From version 2.0.0 , autoDetectCountry is "true" by default and
defaultCountry is a callback country which will be set if something goes
wrong.

Try by adding app:ccp_autoDetectCountry="false" in CCP xml along with
app:ccp_defaultCountry. This will load your default country instead of
detecting from device.

If this does not solve your problem, send me XML code, library version and
testing device.

**Comment by ArmandoGomez** [comment]
Thank you. It works
