### ISSUE TITLE
Setting maximum width programatically

### ISSUE THREAD

**Issue by were-wolf** [hbb20/CountryCodePickerProject#86]
Is it possible to set the width of this component programatically ?

**Comment by hbb20** [comment]
No, width can not be set programmatically due to different lengths of phone code and flag height width ratios. Setting it programmatically may sometimes cut out essential details and won't look appropriate. You can try it by placing ccp in some viewGroup and then change width of this container viewGroup width programmatically.

**Comment by were-wolf** [comment]
Yeah thanks
