### ISSUE TITLE
How to add the close icon at top right corner?

### ISSUE THREAD

**Issue by devtechvalens** [hbb20/CountryCodePickerProject#91]
Hello,
Great work!!

1. How to add the close icon at top right corner?
2. How to make dialog cancelable true? 

Please suggest :+1:

**Comment by hbb20** [comment]
Hi @devtechvalens , 

Isn't the dialog cancellable? When you click device back button it goes away, right? This is what happens when I use it. If this is not the case with you, please tell me your testing device and running versions of android and CCP Library.

Regarding Close button, I think we want the user to select a country from this screen. User should select a country and dialog goes away. It's that simple. In any inevitable situation, user can always go back using device back button. So I don't see a good reason to put an extra element in UI, close button in this case. Does this make sense?

**Comment by hbb20** [comment]
Hey, can you please comment your progress?

**Comment by hbb20** [comment]
Hey. I'm closing this issue. Feel free to open a new issue if required.

**Comment by ajitjati** [comment]
Hey @hbb20 , i have a need for the cross/close button on the dialog. It should be an easy implementation. Plus if anyone needs he can enable it.

**Comment by hbb20** [comment]
Hey @ajitjati  and @devtechvalens . If you upgrade to v2.0.7 and add `app:ccpDialog_showCloseIcon="true"`, then you will be able to see "x" button at the top right corner of dialog.

Refer [wiki](https://github.com/hbb20/CountryCodePickerProject/wiki/XML-Properties#appccpdialog_showcloseicontrue-) for more details.

**Comment by Karthick27O** [comment]
i have implemented this in compose using android view , the close icon is not visible . how to set the color for close icon 
![screenshot_20240405_102058_letsfame_dev](https://github.com/hbb20/CountryCodePickerProject/assets/148423263/7be3a2ba-7cef-4f21-8727-a455def50cc7)
