### ISSUE TITLE
Number format

### ISSUE THREAD

**Issue by jonatanrinckus** [hbb20/CountryCodePickerProject#99]
Is there a way to customize the number format?

Thanks

**Comment by hbb20** [comment]
For now, there is no inbuilt way to do it. What you can do is override the country list for your language. Res of app has high priority than res of libarary. So overriding the same file in your application will override the library's file.

1. Make a copy of your language countryList xml file from [here](https://github.com/hbb20/CountryCodePickerProject/tree/master/ccp/src/main/res/raw) to your app's src/main/res/raw/.
2. Make sure that copied file name must be the same as the original file.
3. Now open the newly created file and replace number format in it.

Let me know if you are planning to do it and if it works?

**Comment by jonatanrinckus** [comment]
I don't understand, you told me to change the file in the raw path, but there is no format, just:
        <country
            name="Ilhas Turcas e Caicos"
            english_name="Turks and Caicos Islands"
            name_code="tc"
            phone_code="1"/>, 

So, what I want is, the ccp format for Brazilian numbers without the country code, is 12 2345-6787 and just it. it's wrong, we have 12 2345-5656 or 12 12345-3423.

So, I have a work arround to fix it, but will be good to know if I can make it work without the work arroud.

I use the https://github.com/jackocnr/intl-tel-input on web, and it work's well, if you wnat to have a look.

Thanks

Att

**Comment by hbb20** [comment]
Oh, earlier I did not understand your question properly. I thought you were looking for different digit system for country codes. Thank you for the explanation.

If you can provide following details, then it will be helpful:
- How do you enter the number? By manually typing or programmatically?
- What is the exact number? What is expected format and what ccp gives you? A screenshot will be great.


For testing, I manually typed all the mentioned numbers in my demo app.

1. For 1223456787 
<img src="https://user-images.githubusercontent.com/4918760/31412718-cb2bbd38-addb-11e7-94c4-ee5775f2d791.png" width="300">

2. For 1223455656
<img src="https://user-images.githubusercontent.com/4918760/31412757-ffe8a45a-addb-11e7-87cf-e6d78d75bd29.png" width="300">

3. For mobile numbers which has "9" right after area code
<img src="https://user-images.githubusercontent.com/4918760/31413108-696b41b6-addd-11e7-9fce-8eb4c22e67d3.png" width="300">

4. For 12123453423
<img src="https://user-images.githubusercontent.com/4918760/31413693-3a0cd468-ade0-11e7-8c62-11ebe08b9305.png" width="300">

(This was not formatted because it is not a valid number according to [wiki](https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil) )

**Comment by jonatanrinckus** [comment]
Yes,. you are right, 12 12345-3423 is invalid, should have a 9, like 12 98345-3423, it work's on some area codes, but it still doesn't work on others area codes, like 47 98345-3423.

I guess this is the problem, I'm testing on 47 area code, since 12/dez/2016  [see here](http://www.anatel.gov.br/Portal/exibirPortalPaginaEspecial.do?org.apache.struts.taglib.html.TOKEN=9594e1d11fbc996d52bda44e608bb744&codItemCanal=1794&pastaSelecionada=2984) ALL brazilians mobile phone numbers must have the 9 in the front, so I guess it must be updated, a Mobile Phone number without the 9, is a invalid number.

**Comment by hbb20** [comment]
Yeah, it seems that 47 98345-3423 is a valid Brazilian phone number but is not formatted.  I also tested this with a new standalone app to test this number but somehow it is not formatting that number. Everything else works well.

Actually, this library uses Google's [PhoneNumberFormattingTextWatcher](
https://developer.android.com/reference/android/telephony/PhoneNumberFormattingTextWatcher.html) for number formatting as the Google keeps an eye on global standards and formatting.  So either there is some reason why it is not formatting or there must be some bug with it.

I am closing this issue because the scope of this project does not contain the solution to this problem. I will keep using PhoneNumberFormattingTextWatcher's latest version. Hopefully, the updated version of Google's PhoneNumberFormattingTextWatcher might solve it.
